# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_behavior_dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddBehavior_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(448, 155)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 16))
        self.label_2.setObjectName("label_2")
        self.add_behavior_to_database_radiobutton = QtWidgets.QRadioButton(Dialog)
        self.add_behavior_to_database_radiobutton.setGeometry(QtCore.QRect(20, 100, 211, 20))
        self.add_behavior_to_database_radiobutton.setObjectName("add_behavior_to_database_radiobutton")
        self.behavior_lineedit = QtWidgets.QLineEdit(Dialog)
        self.behavior_lineedit.setGeometry(QtCore.QRect(90, 20, 321, 21))
        self.behavior_lineedit.setObjectName("behavior_lineedit")
        self.behavior_specifics_lineedit = QtWidgets.QLineEdit(Dialog)
        self.behavior_specifics_lineedit.setGeometry(QtCore.QRect(150, 60, 261, 21))
        self.behavior_specifics_lineedit.setObjectName("behavior_specifics_lineedit")
        self.cancel_pushbutton = QtWidgets.QPushButton(Dialog)
        self.cancel_pushbutton.setGeometry(QtCore.QRect(240, 120, 101, 32))
        self.cancel_pushbutton.setObjectName("cancel_pushbutton")
        self.add_behavior_pushbutton = QtWidgets.QPushButton(Dialog)
        self.add_behavior_pushbutton.setGeometry(QtCore.QRect(330, 120, 101, 32))
        self.add_behavior_pushbutton.setObjectName("add_behavior_pushbutton")

        self.retranslateUi(Dialog)
        self.add_behavior_pushbutton.clicked.connect(self.add_behavior_slot) # type: ignore
        self.cancel_pushbutton.clicked.connect(self.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Behavior:"))
        self.label_2.setText(_translate("Dialog", "Behavior Specifics:"))
        self.add_behavior_to_database_radiobutton.setText(_translate("Dialog", "Add to the behavior database"))
        self.cancel_pushbutton.setText(_translate("Dialog", "Cancel"))
        self.add_behavior_pushbutton.setText(_translate("Dialog", "Add"))
